"""Placed board -> RS-274X Gerber layers + Excellon drill.

Generated directly from pad geometry (positions, shapes, sizes, drills) of
the placed footprints — no KiCad installation needed. Copper layers carry
pad flashes (no tracks yet: routing is not implemented), mask layers mirror
the pads, Edge.Cuts carries the outline, and the drill file covers PTH and
NPTH holes (oval drills become proper G85 slots).

Roundrect/custom pads are approximated by their bounding rectangle; pads
rotated off-axis keep their bounding box. Fine at this fidelity: these
files are geometrically real but the board is unrouted, so they are for
review, not production.
"""

from __future__ import annotations

from pathlib import Path

from .board_gen import Board
from .netlist import Design

LINE_APERTURE = 0.10  # Edge.Cuts outline pen, mm


def write_gerbers(design: Design, board: Board, name: str,
                  out_dir: Path) -> dict[str, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    pads = _absolute_pads(board)

    files: dict[str, Path] = {}
    layers = {
        f"{name}-F_Cu.gtl": [p for p in pads if p["top_cu"]],
        f"{name}-B_Cu.gbl": [p for p in pads if p["bottom_cu"]],
        f"{name}-F_Mask.gts": [p for p in pads if p["top_mask"]],
        f"{name}-B_Mask.gbs": [p for p in pads if p["bottom_cu"]],
    }
    for filename, layer_pads in layers.items():
        path = out_dir / filename
        path.write_text(_gerber_layer(filename, layer_pads, board))
        files[filename] = path

    edge = out_dir / f"{name}-Edge_Cuts.gm1"
    edge.write_text(_edge_cuts(board))
    files[edge.name] = edge

    drill = out_dir / f"{name}-PTH.drl"
    drill.write_text(_excellon(pads, board))
    files[drill.name] = drill
    return files


def _absolute_pads(board: Board) -> list[dict]:
    out = []
    for placement in board.placements:
        for pad in placement.footprint.pads:
            # footprint rotation is always 0 in the current placer
            x = placement.x + pad.x
            y = placement.y + pad.y
            w, h = pad.w, pad.h
            if pad.rot % 180 == 90:
                w, h = h, w
            drill_w, drill_h = pad.drill_w, pad.drill_h
            if pad.rot % 180 == 90 and drill_h:
                drill_w, drill_h = drill_h, drill_w
            layers = set(pad.layers)
            is_tht = pad.kind == "thru_hole"
            is_npth = pad.kind == "np_thru_hole"
            out.append({
                "x": x, "y": y, "w": w, "h": h,
                "shape": pad.shape,
                "drill_w": drill_w, "drill_h": drill_h,
                "top_cu": (is_tht or bool({"F.Cu", "*.Cu"} & layers))
                          and not is_npth,
                "bottom_cu": is_tht,
                "top_mask": (is_tht or bool({"F.Mask", "*.Mask"} & layers))
                            and not is_npth,
                "npth": is_npth,
            })
    return out


def _aperture(pad: dict) -> tuple:
    if pad["shape"] == "circle":
        return ("C", round(pad["w"], 4))
    if pad["shape"] == "oval":
        return ("O", round(pad["w"], 4), round(pad["h"], 4))
    return ("R", round(pad["w"], 4), round(pad["h"], 4))


def _gerber_header(function: str) -> list[str]:
    return [
        "%TF.GenerationSoftware,ChatPCB,chatpcb,0.1*%",
        f"%TF.FileFunction,{function}*%",
        "%FSLAX46Y46*%",
        "%MOMM*%",
        "G04 generated by ChatPCB (placement only, unrouted)*",
        "G01*",
    ]


def _coord(v: float) -> str:
    return str(int(round(v * 1_000_000)))


def _gerber_layer(filename: str, pads: list[dict], board: Board) -> str:
    function = "Copper,L1,Top" if "F_Cu" in filename else (
        "Copper,L2,Bot" if "B_Cu" in filename else (
            "Soldermask,Top" if "F_Mask" in filename else "Soldermask,Bot"))
    lines = _gerber_header(function)
    table: dict[tuple, int] = {}
    for pad in pads:
        table.setdefault(_aperture(pad), 10 + len(table))
    for ap, dcode in table.items():
        if ap[0] == "C":
            lines.append(f"%ADD{dcode}C,{ap[1]:.4f}*%")
        elif ap[0] == "O":
            lines.append(f"%ADD{dcode}O,{ap[1]:.4f}X{ap[2]:.4f}*%")
        else:
            lines.append(f"%ADD{dcode}R,{ap[1]:.4f}X{ap[2]:.4f}*%")
    for pad in pads:
        dcode = table[_aperture(pad)]
        gx = pad["x"]
        gy = board.height - pad["y"]  # KiCad Y-down -> Gerber Y-up
        lines.append(f"D{dcode}*")
        lines.append(f"X{_coord(gx)}Y{_coord(gy)}D03*")
    lines.append("M02*")
    return "\n".join(lines) + "\n"


def _edge_cuts(board: Board) -> str:
    lines = _gerber_header("Profile,NP")
    lines.append(f"%ADD10C,{LINE_APERTURE:.4f}*%")
    lines.append("D10*")
    corners = [
        (0.0, 0.0), (board.width, 0.0),
        (board.width, board.height), (0.0, board.height), (0.0, 0.0),
    ]
    x0, y0 = corners[0]
    lines.append(f"X{_coord(x0)}Y{_coord(board.height - y0)}D02*")
    for x, y in corners[1:]:
        lines.append(f"X{_coord(x)}Y{_coord(board.height - y)}D01*")
    lines.append("M02*")
    return "\n".join(lines) + "\n"


def _excellon(pads: list[dict], board: Board) -> str:
    drilled = [p for p in pads if p["drill_w"] > 0]
    tools: dict[float, int] = {}
    for pad in drilled:
        dia = round(min(pad["drill_w"], pad["drill_h"] or pad["drill_w"]), 3)
        tools.setdefault(dia, len(tools) + 1)
    lines = [
        "M48",
        "; generated by ChatPCB (PTH + NPTH combined)",
        "METRIC,TZ",
    ]
    for dia, tool in sorted(tools.items(), key=lambda kv: kv[1]):
        lines.append(f"T{tool}C{dia:.3f}")
    lines.append("%")
    lines.append("G90")
    lines.append("G05")
    for dia, tool in sorted(tools.items(), key=lambda kv: kv[1]):
        lines.append(f"T{tool}")
        for pad in drilled:
            pdia = round(min(pad["drill_w"], pad["drill_h"] or pad["drill_w"]), 3)
            if pdia != dia:
                continue
            gx = pad["x"]
            gy = board.height - pad["y"]
            if pad["drill_h"] and abs(pad["drill_h"] - pad["drill_w"]) > 1e-6:
                # oval drill -> G85 slot along the long axis
                long_w = pad["drill_w"] > pad["drill_h"]
                half = abs(pad["drill_w"] - pad["drill_h"]) / 2
                dx, dy = (half, 0.0) if long_w else (0.0, half)
                lines.append(
                    f"X{gx - dx:.3f}Y{gy - dy:.3f}G85X{gx + dx:.3f}Y{gy + dy:.3f}"
                )
            else:
                lines.append(f"X{gx:.3f}Y{gy:.3f}")
    lines.append("M30")
    return "\n".join(lines) + "\n"
