"""Design -> .kicad_sch (KiCad schematic with embedded library symbols).

Components are placed on a coarse grid grouped by block. Connectivity is
expressed with global net labels placed exactly on pin endpoints (KiCad
joins coincident points), and explicit no-connect markers on unused pins,
so KiCad's ERC sees a fully-resolved sheet with no dangling pins.
"""

from __future__ import annotations

import uuid

from . import library, sexpr
from .netlist import Design
from .sexpr import Sym

NAMESPACE = uuid.UUID("0d0bdf52-7f43-44a5-9a3a-bbdaf3cbd0c4")

X_STEP = 55.88   # grid pitch between symbol origins, mm (44 mil multiple)
Y_STEP = 45.72
MARGIN = 30.48
COLS = 6


def _uid(*key: str) -> str:
    return str(uuid.uuid5(NAMESPACE, ":".join(key)))


def _snap(v: float) -> float:
    """Snap to KiCad's 1.27mm (50 mil) grid so labels land on pins."""
    return round(v / 1.27) * 1.27


def _fmt(v: float) -> str:
    """Coordinate text with full precision (KiCad joins by exact position)."""
    if abs(v) < 5e-5:
        v = 0.0
    s = f"{v:.4f}".rstrip("0").rstrip(".")
    return s or "0"


def generate_schematic(design: Design, project_name: str) -> str:
    root_uuid = _uid(design.name, "root")
    used_symbols: dict[str, list] = {}
    body: list[list] = []

    for i, comp in enumerate(design.components):
        symbol = library.load_symbol(comp.lib_id)
        used_symbols.setdefault(comp.lib_id, symbol.tree)
        col, row = i % COLS, i // COLS
        ox = _snap(MARGIN + col * X_STEP)
        oy = _snap(MARGIN + row * Y_STEP)
        body.append(_instance(comp, ox, oy, project_name, root_uuid))
        for pin in symbol.pins:
            px = ox + pin.x
            py = oy - pin.y  # symbol Y-up -> sheet Y-down
            net = comp.pin_nets.get(pin.number)
            if net:
                body.append(_global_label(net, px, py, pin.angle, comp.ref,
                                          pin.number))
            else:
                body.append([
                    Sym("no_connect"),
                    [Sym("at"), Sym(_fmt(px)), Sym(_fmt(py))],
                    [Sym("uuid"), _uid(comp.ref, pin.number, "nc")],
                ])

    tree = [
        Sym("kicad_sch"),
        [Sym("version"), Sym("20231120")],
        [Sym("generator"), "chatpcb"],
        [Sym("uuid"), root_uuid],
        [Sym("paper"), "A2"],
        [Sym("title_block"),
         [Sym("title"), design.name],
         [Sym("comment"), Sym("1"),
          "generated by ChatPCB from KiCad official library symbols"]],
        [Sym("lib_symbols"), *[
            _renamed(tree_, lib_id) for lib_id, tree_ in used_symbols.items()
        ]],
        *body,
        [Sym("sheet_instances"),
         [Sym("path"), "/", [Sym("page"), "1"]]],
    ]
    return sexpr.dumps(tree) + "\n"


def _renamed(symbol_tree: list, lib_id: str) -> list:
    out = list(symbol_tree)
    out[1] = lib_id
    return out


def _instance(comp, ox: float, oy: float, project: str, root_uuid: str) -> list:
    symbol = library.load_symbol(comp.lib_id)
    node = [
        Sym("symbol"),
        [Sym("lib_id"), comp.lib_id],
        [Sym("at"), Sym(f"{ox:.2f}"), Sym(f"{oy:.2f}"), Sym("0")],
        [Sym("unit"), Sym("1")],
        [Sym("exclude_from_sim"), Sym("no")],
        [Sym("in_bom"), Sym("yes")],
        [Sym("on_board"), Sym("yes")],
        [Sym("dnp"), Sym("no")],
        [Sym("uuid"), _uid(comp.ref)],
        _property("Reference", comp.ref, ox, oy - 3.81, hide=False),
        _property("Value", comp.value, ox, oy + 3.81, hide=False),
        _property("Footprint", comp.footprint_id, ox, oy, hide=True),
        _property("Datasheet", "", ox, oy, hide=True),
    ]
    for pin in symbol.pins:
        node.append([Sym("pin"), pin.number,
                     [Sym("uuid"), _uid(comp.ref, pin.number)]])
    node.append([
        Sym("instances"),
        [Sym("project"), project,
         [Sym("path"), f"/{root_uuid}",
          [Sym("reference"), comp.ref],
          [Sym("unit"), Sym("1")]]],
    ])
    return node


def _property(name: str, value: str, x: float, y: float, *, hide: bool) -> list:
    effects = [Sym("effects"),
               [Sym("font"), [Sym("size"), Sym("1.27"), Sym("1.27")]]]
    if hide:
        effects.append([Sym("hide"), Sym("yes")])
    return [
        Sym("property"), name, value,
        [Sym("at"), Sym(f"{x:.2f}"), Sym(f"{y:.2f}"), Sym("0")],
        effects,
    ]


def _global_label(net: str, x: float, y: float, pin_angle: float,
                  ref: str, pin_no: str) -> list:
    # Label text should extend away from the symbol body. A pin's angle
    # points from its endpoint toward the body, so flip it; sheet Y-down
    # mirrors the 90/270 cases.
    angle = (pin_angle + 180.0) % 360.0
    if angle in (90.0, 270.0):
        angle = 360.0 - angle
    justify = "right" if angle in (180.0, 270.0) else "left"
    return [
        Sym("global_label"), net,
        [Sym("shape"), Sym("passive")],
        [Sym("at"), Sym(_fmt(x)), Sym(_fmt(y)), Sym(f"{angle:.0f}")],
        [Sym("effects"),
         [Sym("font"), [Sym("size"), Sym("1.27"), Sym("1.27")]],
         [Sym("justify"), Sym(justify)]],
        [Sym("uuid"), _uid(ref, pin_no, "label")],
    ]
